const List listaBares = [
  {
    "evento": "Ozuna X Verano",
    "estado": "Patrocinado",
    "dia": "Miercoles",
    "fecha": "22-04-21 20:00",
    "img": 'assets/portada.jpg',
    "ubicacion": "Formosa,Province of Formosa,Argentina...",
    "organizador": "Organiza Jockey Club",
    "price": "A partir de \$2.000",
  },
  {
    "evento": "Concierto Anuel Verano X",
    "estado": "Patrocinado",
    "dia": "Jueves",
    "fecha": "30-07-22 21:00",
    "img": 'assets/anuel.jpg',
    "ubicacion": "Formosa,Argentina",
    "organizador": "Organiza Gran Rex",
    "price": "A partir de \$5.000",
  },
  {
    "evento": "Candela Gariso Fieston 2021",
    "estado": "Patrocinado",
    "dia": "Jueves",
    "fecha": "30-07-22 21:00",
    "img": 'assets/cande.jpg',
    "ubicacion": "Formosa,Argentina",
    "organizador": "Organiza Molino Rojo",
    "price": "A partir de \$1.500",
  },
  {
    "evento": "Nicky Jam Fieston 2022",
    "estado": "Patrocinado",
    "dia": "Viernes",
    "fecha": "30-07-22 21:00",
    "img": 'assets/nicky.jpg',
    "ubicacion": "Formosa,Argentina",
    "organizador": "Organiza Molino Rojo",
    "price": "A partir de \$1.500",
  },
];
